export const defaultContent = {
 en: {
  nav:['Product','How It Works','How to Use','Grow Better','About','FAQ'], order:'Order Humic', footer:'Grow from the ground up.', copyright:'HUMIC — Home & Garden',
  heroEyebrow:'LIQUID HUMIC ACID FOR HOME GROWERS',heroTitle:'Better soil starts below the surface.',heroBody:'A simple soil-supporting addition for houseplants, flowers, vegetables, herbs, raised beds and container gardens.',heroButton:'Explore Humic',heroIndex:'01 — HUMIC',
  introEyebrow:'THE FOUNDATION OF GROWTH',introTitle:'Great plants begin with great soil.',introBody:'HUMIC is a liquid humic acid product designed for everyday growers. It fits easily into a home-garden routine and helps support the soil environment around the roots where healthy growth begins.',
  benefitsEyebrow:'HUMIC / SOIL',benefitsTitle:'Give your soil more.',benefits:[['Nutrient Support','Helps create soil conditions that support efficient nutrient availability.'],['Root Environment','Supports the soil environment surrounding developing roots.'],['Soil Quality','A practical addition to a thoughtful soil-care routine.'],['Everyday Growing','Made for home gardens, containers, houseplants and small growing spaces.']],
  growEyebrow:'HUMIC / HOME GROWING',growTitle:'Whatever you’re growing, start with the soil.',grow:['Houseplants','Vegetables','Flowers','Raised Beds','Herbs','Containers'],
  productEyebrow:'THE PRODUCT',productTitle:'One liquid. A healthier foundation.',productBody:'HUMIC Liquid Humic Acid is made for simple application around the plants you grow at home. Final concentration, dilution and application details will be added once the product analysis is confirmed.',bottleTop:'LIQUID HUMIC ACID',bottleName:'HUMIC',bottleBottom:'HOME + GARDEN',specLabels:['Concentration','Dilution','Frequency','Sizes'],
  howEyebrow:'HUMIC / HOW IT WORKS',howTitle:'The difference starts underground.',howBody:'Healthy plants depend on the environment around their roots. Humic substances interact with soil and nutrients in ways that can support soil fertility and nutrient availability. HUMIC keeps the message simple: care for the soil, then let the plant do what it does best.',process:['Soil','HUMIC','Roots + nutrients','Growth'],
  useEyebrow:'HUMIC / APPLICATION',useTitle:'Simple enough for everyday growing.',useBody:'Dilute HUMIC according to the final product label, then apply to the soil around your plants. Exact dilution rates, frequency and crop-specific guidance will be published after the final product analysis is available.',useNote:'Current application values remain placeholders until the final product analysis is confirmed.',
  faqEyebrow:'HUMIC / FAQ',faqTitle:'Questions, answered.',faqs:[['What is humic acid?','Humic acid refers to a group of naturally occurring organic substances associated with decomposed plant material and soil organic matter.'],['Can I use HUMIC on houseplants?','The product is intended for home-growing use, including houseplants, once final label directions are confirmed.'],['Can I use it on vegetables and flowers?','Yes, those are core intended uses. Final application rates will follow the confirmed product analysis and label.'],['Can I use it with fertilizer?','Compatibility guidance should follow the final product label. We will publish specific instructions once the formulation details are confirmed.']],ctaEyebrow:'HUMIC',
  orderPage:{eyebrow:'HUMIC / ORDER',title:'Request HUMIC',body:'Send an order request and HUMIC can contact you to confirm availability, price, payment and delivery.',contact:'Contact',back:'Back',labels:['Name','Email','Phone','City','Quantity','Product size','[Enter size]','Message','Send order request','Sending...','Your request has been received. HUMIC can contact you to arrange the order.','Something went wrong. Please try again.']}
 },
 fa: {
  nav:['محصول','نحوه عملکرد','روش مصرف','بهتر پرورش دهید','درباره ما','سؤالات متداول'],order:'سفارش HUMIC',footer:'رشد بهتر، از خاک آغاز می‌شود.',copyright:'HUMIC — خانه و باغچه',
  heroEyebrow:'هیومیک اسید مایع برای پرورش‌دهندگان خانگی',heroTitle:'خاک بهتر، از زیرِ سطح آغاز می‌شود.',heroBody:'راهکاری ساده برای حمایت از خاکِ گیاهان آپارتمانی، گل‌ها، سبزیجات، گیاهان معطر، باغچه‌های کوچک و گلدان‌ها.',heroButton:'آشنایی با هیومیک',heroIndex:'۰۱ — HUMIC',
  introEyebrow:'پایه‌ی رشد',introTitle:'گیاهان سالم از خاک سالم شروع می‌شوند.',introBody:'HUMIC یک محصول هیومیک اسید مایع برای استفاده روزمره در خانه و باغچه‌های کوچک است. استفاده از آن ساده است و به بهبود محیط خاک در اطراف ریشه‌ها کمک می‌کند؛ همان‌جایی که رشد سالم گیاه آغاز می‌شود.',
  benefitsEyebrow:'HUMIC / خاک',benefitsTitle:'به خاک خود بیشتر بدهید.',benefits:[['پشتیبانی از مواد غذایی','به ایجاد شرایط مناسب خاک برای دسترسی بهتر گیاه به مواد غذایی کمک می‌کند.'],['محیط مناسب ریشه','از محیط خاک پیرامون ریشه‌های در حال رشد پشتیبانی می‌کند.'],['کیفیت خاک','افزوده‌ای کاربردی برای یک برنامه منظم و اصولی مراقبت از خاک است.'],['پرورش روزمره','مناسب برای گیاهان آپارتمانی، گلدان‌ها، باغچه‌های خانگی و فضاهای کوچک کشت.']],
  growEyebrow:'HUMIC / پرورش خانگی',growTitle:'هرچه می‌کارید، از خاک شروع کنید.',grow:['گیاهان آپارتمانی','سبزیجات','گل‌ها','باغچه‌های مرتفع','گیاهان معطر','گلدان‌ها'],
  productEyebrow:'محصول',productTitle:'یک محلول؛ پایه‌ای بهتر برای رشد.',productBody:'HUMIC هیومیک اسید مایعی است که برای مصرف ساده در گیاهان خانگی و باغچه طراحی شده است. درصد غلظت، میزان رقیق‌سازی و دستور مصرف نهایی پس از تأیید آنالیز محصول درج خواهد شد.',bottleTop:'هیومیک اسید مایع',bottleName:'HUMIC',bottleBottom:'خانه + باغچه',specLabels:['غلظت','رقیق‌سازی','دفعات مصرف','اندازه‌ها'],
  howEyebrow:'HUMIC / نحوه عملکرد',howTitle:'تفاوت از زیر خاک آغاز می‌شود.',howBody:'سلامت گیاه به محیط اطراف ریشه وابسته است. مواد هیومیکی با خاک و عناصر غذایی برهم‌کنش دارند و می‌توانند از حاصل‌خیزی خاک و دسترسی به مواد غذایی پشتیبانی کنند. پیام HUMIC ساده است: از خاک مراقبت کنید تا گیاه بتواند بهترین رشد خود را داشته باشد.',process:['خاک','HUMIC','ریشه + مواد غذایی','رشد'],
  useEyebrow:'HUMIC / روش مصرف',useTitle:'ساده برای استفاده روزمره.',useBody:'HUMIC را مطابق دستور نهایی روی برچسب محصول رقیق کرده و به خاک اطراف گیاه اضافه کنید. میزان دقیق رقیق‌سازی، دفعات مصرف و راهنمای هر نوع گیاه پس از نهایی شدن آنالیز محصول منتشر خواهد شد.',useNote:'مقادیر فعلی موقت هستند تا آنالیز نهایی محصول تأیید شود.',
  faqEyebrow:'HUMIC / سؤالات متداول',faqTitle:'پاسخ به سؤالات شما.',faqs:[['هیومیک اسید چیست؟','هیومیک اسید به گروهی از مواد آلی طبیعی گفته می‌شود که با تجزیه مواد گیاهی و ماده آلی خاک ارتباط دارند.'],['آیا می‌توانم HUMIC را برای گیاهان آپارتمانی استفاده کنم؟','این محصول برای کاربردهای خانگی، از جمله گیاهان آپارتمانی، در نظر گرفته شده است؛ دستور دقیق مصرف پس از نهایی شدن برچسب محصول اعلام می‌شود.'],['آیا برای سبزیجات و گل‌ها مناسب است؟','بله، این موارد از کاربردهای اصلی محصول هستند. میزان مصرف نهایی بر اساس آنالیز و برچسب تأییدشده اعلام خواهد شد.'],['آیا می‌توان آن را همراه کود استفاده کرد؟','راهنمای سازگاری باید مطابق برچسب نهایی محصول باشد. پس از تأیید جزئیات فرمولاسیون، دستور دقیق منتشر خواهد شد.']],ctaEyebrow:'HUMIC',
  orderPage:{eyebrow:'HUMIC / سفارش',title:'درخواست سفارش HUMIC',body:'فرم را ارسال کنید تا برای هماهنگی موجودی، قیمت، پرداخت و تحویل با شما تماس گرفته شود.',contact:'تماس',back:'بازگشت',labels:['نام','ایمیل','تلفن','شهر','تعداد','اندازه محصول','[اندازه را وارد کنید]','پیام','ارسال درخواست سفارش','در حال ارسال...','درخواست شما ثبت شد. برای هماهنگی با شما تماس گرفته خواهد شد.','ارسال انجام نشد. لطفاً دوباره تلاش کنید.']}
 }
} as const
