/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'order-requests': OrderRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'order-requests': OrderRequestsSelect<false> | OrderRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fa') | ('en' | 'fa')[];
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
    'order-page': OrderPage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'order-page': OrderPageSelect<false> | OrderPageSelect<true>;
  };
  locale: 'en' | 'fa';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-requests".
 */
export interface OrderRequest {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  city?: string | null;
  productSize?: string | null;
  quantity?: number | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'completed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'order-requests';
        value: number | OrderRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-requests_select".
 */
export interface OrderRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  city?: T;
  productSize?: T;
  quantity?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroBody?: string | null;
  heroImage?: (number | null) | Media;
  heroImageAlt?: string | null;
  heroButton?: string | null;
  heroIndex?: string | null;
  introEyebrow?: string | null;
  introTitle?: string | null;
  introBody?: string | null;
  introImage?: (number | null) | Media;
  introImageAlt?: string | null;
  benefitsEyebrow?: string | null;
  benefitsTitle?: string | null;
  benefits?:
    | {
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  growEyebrow?: string | null;
  growTitle?: string | null;
  growCards?:
    | {
        title?: string | null;
        image?: (number | null) | Media;
        imageAlt?: string | null;
        id?: string | null;
      }[]
    | null;
  productEyebrow?: string | null;
  productTitle?: string | null;
  productBody?: string | null;
  productImage?: (number | null) | Media;
  productImageAlt?: string | null;
  bottleTop?: string | null;
  bottleName?: string | null;
  bottleBottom?: string | null;
  concentration?: string | null;
  dilution?: string | null;
  frequency?: string | null;
  sizes?: string | null;
  concentrationLabel?: string | null;
  dilutionLabel?: string | null;
  frequencyLabel?: string | null;
  sizesLabel?: string | null;
  howEyebrow?: string | null;
  howTitle?: string | null;
  howBody?: string | null;
  processSoil?: string | null;
  processHumic?: string | null;
  processRoots?: string | null;
  processGrowth?: string | null;
  useEyebrow?: string | null;
  useTitle?: string | null;
  useBody?: string | null;
  useNote?: string | null;
  faqEyebrow?: string | null;
  faqTitle?: string | null;
  faqs?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaEyebrow?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  instagram?: string | null;
  address?: string | null;
  navProduct?: string | null;
  navHow?: string | null;
  navUse?: string | null;
  navGrow?: string | null;
  navAbout?: string | null;
  navFaq?: string | null;
  orderButton?: string | null;
  footerLine?: string | null;
  copyrightLine?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-page".
 */
export interface OrderPage {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  body?: string | null;
  contactLabel?: string | null;
  backLabel?: string | null;
  nameLabel?: string | null;
  emailLabel?: string | null;
  phoneLabel?: string | null;
  cityLabel?: string | null;
  quantityLabel?: string | null;
  sizeLabel?: string | null;
  sizePlaceholder?: string | null;
  messageLabel?: string | null;
  submitLabel?: string | null;
  sendingLabel?: string | null;
  successMessage?: string | null;
  errorMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroBody?: T;
  heroImage?: T;
  heroImageAlt?: T;
  heroButton?: T;
  heroIndex?: T;
  introEyebrow?: T;
  introTitle?: T;
  introBody?: T;
  introImage?: T;
  introImageAlt?: T;
  benefitsEyebrow?: T;
  benefitsTitle?: T;
  benefits?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  growEyebrow?: T;
  growTitle?: T;
  growCards?:
    | T
    | {
        title?: T;
        image?: T;
        imageAlt?: T;
        id?: T;
      };
  productEyebrow?: T;
  productTitle?: T;
  productBody?: T;
  productImage?: T;
  productImageAlt?: T;
  bottleTop?: T;
  bottleName?: T;
  bottleBottom?: T;
  concentration?: T;
  dilution?: T;
  frequency?: T;
  sizes?: T;
  concentrationLabel?: T;
  dilutionLabel?: T;
  frequencyLabel?: T;
  sizesLabel?: T;
  howEyebrow?: T;
  howTitle?: T;
  howBody?: T;
  processSoil?: T;
  processHumic?: T;
  processRoots?: T;
  processGrowth?: T;
  useEyebrow?: T;
  useTitle?: T;
  useBody?: T;
  useNote?: T;
  faqEyebrow?: T;
  faqTitle?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  ctaEyebrow?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  contactEmail?: T;
  contactPhone?: T;
  instagram?: T;
  address?: T;
  navProduct?: T;
  navHow?: T;
  navUse?: T;
  navGrow?: T;
  navAbout?: T;
  navFaq?: T;
  orderButton?: T;
  footerLine?: T;
  copyrightLine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-page_select".
 */
export interface OrderPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  body?: T;
  contactLabel?: T;
  backLabel?: T;
  nameLabel?: T;
  emailLabel?: T;
  phoneLabel?: T;
  cityLabel?: T;
  quantityLabel?: T;
  sizeLabel?: T;
  sizePlaceholder?: T;
  messageLabel?: T;
  submitLabel?: T;
  sendingLabel?: T;
  successMessage?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}